src/Imi.Project.Vue/Models/ErrorViewModel.cs
using System;

namespace Imi.Project.Vue.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Imi.Project.Vue/Controllers/BrandsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Imi.Project.Vue.Controllers
{
    public class BrandsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Imi.Project.Vue.Controllers
{
    public class CategoriesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/HomeController.cs
using Imi.Project.Vue.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Imi.Project.Vue.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
        
        public IActionResult Logout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Imi.Project.Vue/Controllers/JokesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Imi.Project.Vue.Controllers
{
    public class JokesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Imi.Project.Vue.Controllers
{
    public class ProductsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/SubcategoriesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Imi.Project.Vue.Controllers
{
    public class SubcategoriesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Views/Brands/Index.cshtml
@{
    ViewData["Title"] = "Brands Page";
}

<div>
    <h2>Brands</h2>
</div>

<div id="app" class="row">
    <div class="col-md-12">
        <div class="alert alert-info" v-if="feedback">
            {{feedback}}
        </div>
    </div>
    <div class="col-md-12 flex-column">
        <div>
            <button class="btn btn-info" style="margin: 15px;" v-on:click.prevent="toEditMode(false)">Add</button>
        </div>
        <div class="col-md-6  float-left">
            <ul class="list-group">
                <li class="list-group-item text-center" style="margin-bottom:5px;" v-for="brand in brands" v-on:click="getBrandDetails(brand)">
                    <div>
                        <figure>
                            <img v-bind:src="brand.image" width="150" />
                        </figure>
                    </div>
                    <div>
                        <label>{{brand.name}}</label>
                    </div>
                </li>
            </ul>
        </div>
        <div class="col-md-6 float-left">
            <div v-if="currentBrand">
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" v-model="currentBrand.name" v-bind:readonly="isReadOnly" />
                </div>
                <div class="form-group">
                    <label>Image</label>
                    <figure class="text-center">
                        <img v-bind:src="currentBrand.image" width="120" />
                    </figure>
                    <div class="form-group">
                        <label>
                            Add image 
                            <input type="file" accept="image/*" id="file-input" class="form-control" />
                        </label>
                    </div>
                </div>
                <div class="btn-group">
                    <button class="btn btn-warning" v-if="isReadOnly" v-on:click.prevent="toEditMode(true)">Edit</button>
                    <button class="btn btn-warning" v-if="!isReadOnly" v-on:click.prevent="saveBrand">Save</button>
                    <button class="btn btn-primary" v-if="!isReadOnly" v-on:click.prevent="isReadOnly = true">Cancel</button>
                    <button class="btn btn-danger" v-on:click.prevent="deleteBrand">Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>

    <script>
        var apiBase = 'https://localhost:5001/api/';
        var axiosConfig;
        var token = localStorage.getItem('jwtToken');
        if (token != null) {
            axios.defaults.headers.common['Authorization'] = 'Bearer ' + token;
        }

        var app = new Vue({
            el: '#app',
            data: {
                brands: null,
                currentBrand: null,
                selectedImage: null,
                isReadOnly: true,
                feedback: '',
                statuses: [{ name: 'Active' }, { name: 'Inactive' }],
                isEditMode: false,
                isDeleteMode: false,
            },
            created: function () {
                var self = this;
                self.fetchBrands();
            },
            methods: {
                fetchBrands: function () {
                    var self = this;
                    axios.get(apiBase + 'Brands')
                        .then(function (response) {
                            console.log(response.data);
                            self.brands = response.data;
                        })
                        .catch(function (error) {
                            console.error(error);
                        });
                },
                toEditMode: function (isEditMode) {
                    var self = this;
                    self.isReadOnly = false;
                    self.isEditMode = isEditMode;

                    if (!self.isEditMode) {
                        self.currentBrand = {
                            name: "",
                            id: "00000000-0000-0000-0000-000000000000",
                            image: "https://i.postimg.cc/1X9YcxyL/Placeholder.jpg",
                        }
                    }
                },
                saveBrand: function () {
                    var self = this;
                    if (self.isEditMode) {
                        console.log('edit brand:', self.currentBrand);

                        var url = (`${apiBase}Brands`);
                        axios.put(url, self.currentBrand, axiosConfig)
                            .then(function (response) {
                                console.log('edited brand response: ', response)
                            })
                            .catch(function (error) {
                                console.error(error);
                            })
                            .then(function () {
                                self.isReadOnly = true;
                                self.feedback = `Brand ${self.currentBrand.name} has been modified`;
                                setTimeout(function () { self.feedback = null; }, 3000);
                            });
                    }
                    else {
                        console.log('add brand:', self.currentBrand);

                        var url = `${apiBase}Brands`;
                        axios.post(url, self.currentBrand, axiosConfig)
                            .then(function (response) {
                                console.log('added brand response: ', response)
                            })
                            .catch(function (error) {
                                console.error(error);
                            })
                            .then(function () {
                                self.isReadOnly = true;
                                self.feedback = `Brand ${self.currentBrand.name} has been created`;
                                setTimeout(function () { self.feedback = null; }, 3000);
                            });
                    }
                },
                deleteBrand: function () {
                    var self = this;
                    var url = `${apiBase}Brands/${self.currentBrand.id}`;

                    axios.delete(url, axiosConfig)
                        .then(function (response) {
                            self.brands.forEach(function (brand, i) {
                                if (brand.id === self.currentBrand.id) {
                                    self.brands.splice(i, 1);
                                }
                            })
                        })
                        .catch(function (error) { console.error(error); })
                        .then(function () {
                            self.feedback = `Brand ${self.currentBrand.name} has been deleted successfully!`;
                            setTimeout(function () { self.feedback = null; }, 3000);
                        });
                },
                getBrandDetails: function (selectedBrand) {
                    var self = this;

                    self.currentBrand = selectedBrand;
                    window.scrollTo(0, 0);
                },
                selectImage(event) {
                    var self = this;
                    console.log("test select image", event);
                    self.selectedImage = event.target.files[0];
                    console.log(self.selectedImage);
                },
                uploadImage: function (file, onUploadProgress) {
                    var url = `${apiBase}Brands/${currentBrand.id}/image`;
                    let formData = new FormData();
                    formData.append("image", this.newImage, this.newImage.name);
                    axios.post(url, formData)
                        .then(response => {
                            console.log(response);
                        })
                }
            }
        });
    </script>
}

src/Imi.Project.Vue/Views/Categories/Index.cshtml
@{
    ViewData["Title"] = "Categories Page";
}

<div>
    <h2>Categories</h2>
</div>

<div id="app" class="row">
    <div class="col-md-12">
        <div class="alert alert-info" v-if="feedback">
            {{feedback}}
        </div>
    </div>
    <div class="col-md-12 flex-column">
        <div>
            <button class="btn btn-info" style="margin: 15px;" v-on:click.prevent="toEditMode(false)">Add</button>
        </div>
        <div class="col-md-6  float-left">
            <ul class="list-group">
                <li class="list-group-item text-center" style="margin-bottom:5px;" v-for="category in categories" v-on:click="getCategoryDetails(category)">
                    <div>
                        <figure>
                            <img v-bind:src="category.image" width="150" />
                        </figure>
                    </div>
                    <div>
                        <label>{{category.name}}</label>
                    </div>
                </li>
            </ul>
        </div>
        <div class="col-md-6 float-left">
            <div v-if="currentCategory">
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" v-model="currentCategory.name" v-bind:readonly="isReadOnly" />
                </div>
                <div class="form-group">
                    <label>Image</label>
                    <figure class="text-center">
                        <img v-bind:src="currentCategory.image" width="120" />
                    </figure>
                    <div class="form-group">
                        <label>
                            Add image
                            <input type="file" accept="image/*" id="file-input" class="form-control" />
                        </label>
                    </div>
                </div>
                <div class="btn-group">
                    <button class="btn btn-warning" v-if="isReadOnly" v-on:click.prevent="toEditMode(true)">Edit</button>
                    <button class="btn btn-warning" v-if="!isReadOnly" v-on:click.prevent="saveCategory">Save</button>
                    <button class="btn btn-primary" v-if="!isReadOnly" v-on:click.prevent="isReadOnly = true">Cancel</button>
                    <button class="btn btn-danger" v-on:click.prevent="deleteCategory">Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>

    <script>
        var apiBase = 'https://localhost:5001/api/';
        var axiosConfig;
        var token = localStorage.getItem('jwtToken');
        if (token != null) {
            axios.defaults.headers.common['Authorization'] = 'Bearer ' + token;
        }

        var app = new Vue({
            el: '#app',
            data: {
                categories: null,
                currentCategory: null,
                selectedImage: null,
                isReadOnly: true,
                feedback: '',
                statuses: [{ name: 'Active' }, { name: 'Inactive' }],
                isEditMode: false,
                isDeleteMode: false,
            },
            created: function () {
                var self = this;
                self.fetchCategories();
            },
            methods: {
                fetchCategories: function () {
                    var self = this;
                    axios.get(apiBase + 'Categories')
                        .then(function (response) {
                            console.log(response.data);
                            self.categories = response.data;
                        })
                        .catch(function (error) {
                            console.error(error);
                        });
                },
                toEditMode: function (isEditMode) {
                    var self = this;
                    self.isReadOnly = false;
                    self.isEditMode = isEditMode;

                    if (!self.isEditMode) {
                        self.currentCategory = {
                            name: "",
                            id: "00000000-0000-0000-0000-000000000000",
                            image: "https://i.postimg.cc/1X9YcxyL/Placeholder.jpg",
                        }
                    }
                },
                saveCategory: function () {
                    var self = this;
                    if (self.isEditMode) {
                        console.log('edit category:', self.currentCategory);

                        var url = (`${apiBase}Categories`);
                        axios.put(url, self.currentCategory, axiosConfig)
                            .then(function (response) {
                                console.log('edited category response: ', response)
                            })
                            .catch(function (error) {
                                console.error(error);
                            })
                            .then(function () {
                                self.isReadOnly = true;
                                self.feedback = `Category ${self.currentCategory.name} has been modified`;
                                setTimeout(function () { self.feedback = null; }, 3000);
                            });
                    }
                    else {
                        console.log('add category:', self.currentCategory);

                        var url = `${apiBase}Categories`;
                        axios.post(url, self.currentCategory, axiosConfig)
                            .then(function (response) {
                                console.log('added category response: ', response)
                            })
                            .catch(function (error) {
                                console.error(error);
                            })
                            .then(function () {
                                self.isReadOnly = true;
                                self.feedback = `Category ${self.currentCategory.name} has been created`;
                                setTimeout(function () { self.feedback = null; }, 3000);
                            });
                    }
                },
                deleteCategory: function () {
                    var self = this;
                    var url = `${apiBase}Categories/${self.currentCategory.id}`;

                    axios.delete(url, axiosConfig)
                        .then(function (response) {
                            self.categories.forEach(function (category, i) {
                                if (category.id === self.currentCategory.id) {
                                    self.categories.splice(i, 1);
                                }
                            })
                        })
                        .catch(function (error) { console.error(error); })
                        .then(function () {
                            self.feedback = `Category ${self.currentCategory.name} has been deleted successfully!`;
                            setTimeout(function () { self.feedback = null; }, 3000);
                        });
                },
                getCategoryDetails: function (selectedCategory) {
                    var self = this;

                    self.currentCategory = selectedCategory;
                    window.scrollTo(0, 0);
                },
                selectImage(event) {
                    var self = this;
                    console.log("test select image", event);
                    self.selectedImage = event.target.files[0];
                    console.log(self.selectedImage);
                },
                uploadImage: function (file, onUploadProgress) {
                    var url = `${apiBase}Categories/${currentCategory.id}/image`;
                    let formData = new FormData();
                    formData.append("image", this.newImage, this.newImage.name);
                    axios.post(url, formData)
                        .then(response => {
                            console.log(response);
                        })
                }
            }
        });
    </script>
}

src/Imi.Project.Vue/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<header>
    <h2>Guitarshop</h2>
</header>
<section>
    <figure style="background-image:url('/images//Background/guitar.jpg');background-size:cover;background-repeat:no-repeat;background-attachment:fixed;width:auto;height:600px">
        <ul class="list-group list-unstyled list-style-homepage" style="padding:10px;background-color:black;border:solid 2px white;border-bottom-right-radius:10px;width:100px;">
            <li><a href="/Home/Login" style="color:snow;text-decoration:none;">Login</a></li>
            <li><a href="/Home/Register" style="color:snow;text-decoration:none;">Register</a></li>
        </ul>
    </figure>
</section>

src/Imi.Project.Vue/Views/Home/Login.cshtml
<div>
    <h2>Login</h2>
</div>

<div id="app">
    <p v-bind:title="message">{{message}}</p>
    <div class="text-center">
        <div v-if="!loggedIn" class="col-md-6">
            <div class="form-group">
                <h5>Username</h5>
                <input type="text" v-model="loginForm.username" class="form-control">
            </div>
            <div class="form-group">
                <h5>Password</h5>
                <input type="password" v-model="loginForm.password" class="form-control">
            </div>
            <div class="form-group">
                <button v-on:click="loginUser" class="btn-dark">Login</button>
            </div>
        </div>
        <div v-else>
            <figure style="background-image:url('/images//Background/guitar.jpg');background-size:cover;background-repeat:no-repeat;background-attachment:fixed;width:auto;height:600px"/>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>

    <script>
        var apiBase = 'https://localhost:5001/api/';
        var apiURL = apiBase + 'auth/login';
        let jwtToken = '';
        var lastPage = 0;

        var app = new Vue({
            el: '#app',
            data: {
                message: 'Hello! Please login below',
                loggedIn: false,
                loginForm: {
                    username: 'admin@guitarshop.com',
                    password: 'Test123?',
                },
            },
            methods: {
                loginUser: function () {
                    var self = this;
                    var logLogin = function () {
                        console.log(apiURL);
                        console.log(self.loginForm);
                        axios.post(apiURL, self.loginForm)
                            .then(function (response) {
                                axios.defaults.headers.common['Authorization'] = 'Bearer ' + response.data.token;
                                console.log(response.data.jwtToken);
                                localStorage.setItem('jwtToken', response.data.jwtToken);
                                alert(`User ${self.loginForm.username} logged in successfully!`);

                                self.message = `Hi, ${self.loginForm.username}!`;
                                self.loginForm.username = "";
                                self.loginForm.password = "";
                                self.loggedIn = true;
                            })
                            .catch(function (error) {
                                console.error(error);
                                if (error.response)
                                    alert(`User ${self.loginForm.username} log in failed!`);
                            });
                    }
                    logLogin();
                }
            }
        })
    </script>
}

src/Imi.Project.Vue/Views/Home/Logout.cshtml
<div>
    <h2>Logout</h2>
</div>

<div id="app">
    <div class="text-center">
        <p v-bind:title="message">{{message}}</p>
        <div class="form-group">
            <button v-on:click="logoutUser" class="btn-dark">Logout</button>
        </div>
    </div>
    <div>
        <figure style="background-image:url('/images//Background/guitar.jpg');background-size:cover;background-repeat:no-repeat;background-attachment:fixed;width:auto;height:600px" />
    </div>

</div>
@section scripts{
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>

    <script>
        var app = new Vue({
            el: '#app',
            data: {
                message: 'Are you sure you want to log out?',
                loggedIn: true,
            },
            methods: {
                logoutUser: function () {
                    var self = this;
                    localStorage.setItem('jwtToken', "");
                    alert(`You logged out successfully!`);
                    self.message = `Logged out!`;                    
                }
            }
        })
    </script>
}

src/Imi.Project.Vue/Views/Jokes/Index.cshtml
@{
    ViewData["Title"] = "Jokes Page";
}

<div>
    <h2>Jokes</h2>
</div>

<div id="app">
    <div>
        <button class="btn btn-info" v-on:click.prevent="fetchRandomJoke">New random joke</button>
    </div>
    <br />
    <div class="card">
        <h3 class="card-header">Joke of the day</h3>
        <article class="card-body">
            <section class="text-center" v-for="joke in jokeOfTheDay">
                <div>
                    <h4>{{joke.joke.title}}</h4>
                </div>
                <div>
                    <p>{{joke.joke.text}}</p>
                </div>
                <div>
                    <p class="font-italic">{{joke.joke.date}}</p>
                </div>
            </section>
        </article>
    </div>
    <br />
    <div class="card">
        <h3 class="card-header">Random joke</h3>
        <article class="card-body">
            <section class="text-center" v-for="joke in randomJoke">
                <div>
                    <p>{{joke}}</p>
                </div>
            </section>
        </article>
    </div>
</div>

@section scripts{
<script src="~/lib/vue/vue.js"></script>
<script src="~/lib/axios/axios.min.js"></script>

<script>
    var apiJokeOfTheDay = 'https://api.jokes.one/Jod';
    var apiRandomJoke = 'https://geek-jokes.sameerkumar.website/api?format=json';

    var app = new Vue({
        el: '#app',
        data: {
            jokeOfTheDay: null,
            randomJoke: null,
        },
        created: function () {
            var self = this;
            self.fetchJokeOfTheDay();
            self.fetchRandomJoke();
        },
        methods: {
            fetchJokeOfTheDay: function () {
                var self = this;
                axios.get(apiJokeOfTheDay)
                    .then(function (response) {
                        console.log('joke of the day:');
                        console.log(response);
                        self.jokeOfTheDay = response.data.contents.jokes;
                    })
                    .catch(function (error) {
                        console.error(error);
                    });
            },
            fetchRandomJoke: function () {
                var self = this;
                axios.get(apiRandomJoke)
                    .then(function (response) {
                        console.log('random joke:');
                        console.log(response);
                        self.randomJoke = response.data;
                    })
                    .catch(function (error) {
                        console.error(error);
                    });
            },
        }
    });
</script>
}

src/Imi.Project.Vue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Guitarshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Guitarshop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brands" asp-action="Index">Brands</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subcategories" asp-action="Index">Subcategories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="Index">Jokes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Guitarshop - <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>